### PR TITLE
Add GitHub action for tests and issue templates

### PR DESCRIPTION
**Pull request by justaddcoffee**

### CODE REVIEW

**Review by caufieldjh — COMMENTED** [review]
Just need to add the sonar-project.properties I think

**Comment by justaddcoffee** [comment]
Yep, just added

**Comment by caufieldjh** [comment]
I don't see a way to fix the setting Sonarcloud is complaining about, but everything else looks fine.

**Comment by justaddcoffee** [comment]
The setting Sonarcloud was complaining about is in the UI - I think I've fixed this

**Pull request merged**
